name: ci-build-push
on:
push:
branches: [ main ]


jobs:
build:
runs-on: ubuntu-latest
permissions:
id-token: write
contents: read
env:
AWS_REGION: us-east-1
AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
steps:
- uses: actions/checkout@v4


- name: Set up Python
uses: actions/setup-python@v5
with:
python-version: '3.11'


- name: Build and run tests
run: |
python -m pip install -r sample-fastapi-app/requirements.txt
pytest -q || true


- name: Scan repo with Trivy
uses: aquasecurity/trivy-action@0.20.0
with:
scan-type: 'fs'
severity: 'CRITICAL,HIGH'


- name: Configure AWS credentials via OIDC
uses: aws-actions/configure-aws-credentials@v4
with:
role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GitHubActionsOIDCRole
aws-region: ${{ env.AWS_REGION }}


- name: Login to ECR
uses: aws-actions/amazon-ecr-login@v2


- name: Build and push Docker image
run: |
IMAGE="${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/sample-fastapi:${{ github.sha }}"
docker build -t "$IMAGE" sample-fastapi-app/
docker push "$IMAGE"
